Repository BloomBeat/SignBloom3D, pull requests merged in 2024-08, with the labels that each got.

#1 Search and filters route
  README.md
  server/configs/db.config.js
  server/controllers/vocabController.js
  server/index.js
  server/models/category.js
  server/routes/vocab.js
Labels: enhancement

#3 Ticket managemnet system API
  pnpm-lock.yaml
  server/controllers/ticketController.js
  server/index.js
  server/models/ticket.js
  server/package.json
  server/routes/ticket.js
  server/routes/vocab.js
Labels: enhancement

#2 Component intialization
  client/package.json
  client/public/SignBloom3DLogo.png
  client/src/components/Botton.jsx
  client/src/components/FilterCategory.jsx
  client/src/components/FilterInterpreter.jsx
  client/src/components/FilterWordtype.jsx
  client/src/components/Navbaruser.jsx
  client/src/components/Searchbar.jsx
  client/src/general/RoutePaths.jsx
  client/src/general/Router.jsx
  client/src/home/Home.jsx
  client/src/pages/admin/components/FilterStatus.jsx
  client/src/pages/admin/components/FilterTime.jsx
  client/src/pages/home/HomePage.jsx
  client/tailwind.config.js
  pnpm-lock.yaml
Labels: documentation

#4 User&authen
  pnpm-lock.yaml
  server/configs/db.config.js
  server/controllers/userController.js
  server/index.js
  server/middlewares/authUser.js
  server/middlewares/validateLogin.js
  server/middlewares/validateRegister.js
  server/models/user.js
  server/package.json
  server/routes/user.js
Labels: enhancement

#6 CORS and PNPM-LOCK Fixed
  pnpm-lock.yaml
  server/index.js
Labels: bug, enhancement

#7 Home page
  client/src/components/Botton.jsx
  client/src/components/FilterInterpreter.jsx
  client/src/components/Searchbar.jsx
  client/src/pages/home/HomePage.jsx
  server/controllers/vocabController.js
Labels: documentation

#9 Display a vocabulary API
  server/controllers/vocabController.js
  server/routes/vocab.js
Labels: enhancement

#8 getCategory
  server/controllers/vocabController.js
  server/routes/vocab.js
Labels: enhancement

#10 feat-Pagination integration with Ticket and Vocab
  server/controllers/ticketController.js
  server/controllers/vocabController.js
Labels: enhancement

#5 Vocabulary page
  client/src/components/Botton.jsx
  client/src/components/FilterCategory.jsx
  client/src/components/FilterInterpreter.jsx
  client/src/components/FilterWordtype.jsx
  client/src/components/Navbaruser.jsx
  client/src/components/Searchbar.jsx
  client/src/general/Router.jsx
  client/src/index.css
  client/src/pages/home/HomePage.jsx
  client/src/pages/vocabulary/VocabularyPage.jsx
  client/src/pages/vocabulary/_components/Dropdown.jsx
  client/src/pages/vocabulary/_components/Searchbar.jsx
  client/tailwind.config.js
  pnpm-lock.yaml
  server/controllers/ticketController.js
  server/routes/vocab.js
Labels: documentation

#16 change-endpoint fix-auth
  server/controllers/ticketController.js
  server/controllers/vocabController.js
  server/middlewares/authUser.js
Labels: enhancement

#18 TicketPage Completed
  client/package.json
  client/src/components/FilterCategory.jsx
  client/src/components/FilterWordtype.jsx
  client/src/components/Navbaruser.jsx
  client/src/components/Searchbar.jsx
  client/src/components/TitleHero.jsx
  client/src/general/RoutePaths.jsx
  client/src/general/Router.jsx
  client/src/hooks/api.js
  client/src/index.css
  client/src/pages/admin/AdminTicketPage.jsx
  client/src/pages/admin/components/FilterStatus.jsx
  client/src/pages/admin/components/FilterTime.jsx
  client/src/pages/admin/components/NavbarAdmin.jsx
  client/src/pages/admin/components/SeachbarAdmin.jsx
  client/src/pages/home/HomePage.jsx
  client/src/pages/vocabulary/VocabularyPage.jsx
  client/src/pages/vocabulary/_components/Searchbar.jsx
  pnpm-lock.yaml
  server/controllers/ticketController.js
  server/package.json
Labels: documentation

#21 Change Status to Thai / Add filter delay
  client/src/components/FilterCategory.jsx
  client/src/components/FilterWordtype.jsx
  client/src/pages/admin/AdminTicketPage.jsx
  client/src/pages/admin/components/FilterStatus.jsx
  client/src/pages/vocabulary/VocabularyPage.jsx
Labels: bug, documentation
